export const FILL_PASSWORD = 'FILL_PASSWORD';
export const FILL_USERNAME_PASSWORD = 'FILL_USERNAME_PASSWORD';
export const GET_CREDENTIALS = 'GET_CREDENTIALS';
export const REMEMBER_CREDENTIALS = 'REMEMBER_CREDENTIALS';
export const ACTIVATE_PASSWORD_GENERATOR = 'ACTIVATE_PASSWORD_GENERATOR';
export const GET_OPTIONS = 'GET_OPTIONS';
